### ISSUE TITLE
Fails to install on FBSD

### ISSUE THREAD

**Issue by paulprocacci** [vrurg/perl6-IP-Addr#6] opened 2021-10-06 01:49 UTC
FreeBSD yep.myhome 13.0-RELEASE-p3 FreeBSD 13.0-RELEASE-p3 #0: Tue Jun 29 19:46:20 UTC 2021     root@amd64-builder.daemonology.net:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64

# zef install IP::Addr
===> Searching for: IP::Addr
===> Updating fez mirror: http://360.zef.pm/
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated fez mirror: http://360.zef.pm/
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Searching for missing dependencies: Test::When, p6doc, Pod::To::Markdown
===> Searching for missing dependencies: Pod::To::HTML:auth<github:Raku>, Doc::TypeGraph, Pod::To::HTML, Pod::To::BigPage
===> Searching for missing dependencies: HTTP::UserAgent, IO::Socket::SSL, Template::Mustache, Pod::Load:ver<0.4.0+>, OO::Monitors, Test::Output, dot:from<bin>
===> Failed to find dependencies: dot:from<bin>
Failed to resolve some missing dependencies (use e.g. --exclude="dot" to skip)
root@nas:~/lucera-vm # zef install IP::Addr
===> Searching for: IP::Addr
===> Searching for missing dependencies: Test::When, p6doc, Pod::To::Markdown
===> Searching for missing dependencies: Pod::To::HTML:auth<github:Raku>, Doc::TypeGraph, Pod::To::HTML, Pod::To::BigPage
===> Searching for missing dependencies: HTTP::UserAgent, IO::Socket::SSL, Template::Mustache, Pod::Load:ver<0.4.0+>, OO::Monitors, Test::Output, dot:from<bin>
===> Failed to find dependencies: dot:from<bin>
Failed to resolve some missing dependencies (use e.g. --exclude="dot" to skip)

**Comment by vrurg** [comment] 2021-10-06 14:54
The problem is caused by one of the dependencies. Not sure which one, but certainly one of Pod::To::HTML:authgithub:Raku, Doc::TypeGraph, Pod::To::HTML, Pod::To::BigPage.

Anyway, I just realized that p6doc should've been removed from the dependencies long time ago.

Thanks!

**Comment by vrurg** [comment] 2021-10-06 20:18
Fixed with v0.0.4 release.

**Closed as completed by vrurg** 2021-10-06 20:18 UTC
